# Generated by Django 6.0 on 2026-01-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnectApp', '0002_medicalrecord_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladminprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
