# Generated by Django 6.0 on 2026-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnectApp', '0003_hospitaladminprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
