# Generated by Django 6.0 on 2026-01-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnectApp', '0006_alter_patientprofile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='instructions',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MediConnectApp.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicines',
            field=models.TextField(),
        ),
    ]
