# Generated by Django 6.0 on 2026-03-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnectApp', '0008_doctoravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladminprofile',
            name='hospital_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
