# Generated by Django 5.0.6 on 2026-04-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnectApp', '0009_alter_hospitaladminprofile_hospital_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='allergies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='diseases',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='profile/'),
        ),
    ]
