# Generated by Django 5.0.6 on 2026-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediConnectApp', '0012_alter_patientprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/patient'),
        ),
    ]
